              - name: Profile Readme Development Stats
                uses: anmol098/waka-readme-stats@V3
            

name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master  #PLEASE USE MASTER BRANCH
        with:
          WAKATIME_API_KEY: waka_d1016a10-c945-47bd-87cb-5ab9e714f5aa
          GH_TOKEN: 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
          SHOW_PROJECTS: "False"
          SHOW_SHORT_INFO: "True"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_LOC_CHART: "False"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_COMMIT: "True"
          SHOW_OS: "True"
          LOCALE: "en"

